# Base image
FROM node:18

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all relevant folders
COPY app ./app
COPY components ./components
COPY utils ./utils

# Expose the default Metro server port
EXPOSE 8081

# Start the Metro bundler
CMD ["npm", "start"]
